sh API-Install.sh
sh AutoPixie-WPS-Scan-Tool-Install.sh
sh CMSmap-Install.sh
sh Crazy-Banner.sh
sh Crontab-Install.sh
sh Dorks-Eye-Install.sh
sh Dropbear-Install.sh
sh FTP-Install.sh
sh FZF-Install.sh
sh Fish-Install.sh
sh Games-Install.sh
sh Heroku-Install.sh
sh Install-p10k-Font.sh
sh MOSH-Install.sh
sh Metasploit-Install.sh
sh Neofetch-Install.sh
sh Oh-My-Termux-Install.sh
sh OpenSSH-Install.sh
sh PRoot-Install.sh
sh Setting-up-HTTP-Server.sh
sh Setting-up-Public-Key-Authentication.sh
sh Speak-Engine-Install.sh
sh Speak-Install.sh
sh Sudo-Termux-Install.sh
sh Terminal-Look-Awesome-Color-Font-Style.sh
sh Termux-Docker-Install.sh
sh Termux-Python.sh
sh aliases.sh
sh chromeos-qemu.sh
sh oh-my-fish.sh
sh setup-pointless-repo.sh
sh Lazymux-Full-Install.sh
